name: Update Docs-ui Tag and Create PR

on:
  workflow_dispatch:
    inputs:
      image_version:
        description: 'Enter the new image version tag, e.g.: v0.2.22'
        required: true

jobs:
  update-tag-and-deploy:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ github.token }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor }}@users.noreply.github.com"
        git config push.default current
        git config push.autoSetupRemote true

    - name: Create a unique branch
      run: |
        unique_branch="update-tag-${{ github.run_id }}"
        git checkout -b $unique_branch

    - name: Update images.libsonnet file
      run: |
        sed -i '\|docs_ui: PATH.image { name: '\''NAME'\''|s|tag: .*|tag: '\''${{ github.event.inputs.image_version }}'\'', source: '\''PLACEHOLDER'\'' },|' images.libsonnet

    - name: Commit and Push Changes
      run: |
        git add images.libsonnet
        git commit -m "Update docs-ui tag in images.libsonnet"
        git push origin $unique_branch

    - name: Create Label 'automated'
      run: gh label create automated --color F29513 --force

    - name: Create Pull Request in repo-component-platform
      run: |
        gh pr create --base main --title "Update tag in images.libsonnet" --body "This pull request updates docs-ui tag in images.libsonnet" --label "automated"

    # This step can break system manifest build. Only should be opened if you are sure that there is no other change than docs-ui tag
    # While automerge is closed, just visit the PR url provided in the workflow log, then check/merge manually.
    # - name: Auto-Merge Pull Request 
    #   run: gh pr merge --merge --auto -d
